services:
  db:
    image: postgres:latest
    # Note we are using a custom port
    ports:
      - "5433:5433"
    environment:
      - PGPORT=5433
      - POSTGRES_USER=country
      - POSTGRES_PASSWORD=countryPassword
      - POSTGRES_DB=countries
